### PR TITLE
Setup Folders Structure

### PR DESCRIPTION
**Pull request by a-da**

### CODE REVIEW

**Comment by shawnsarwar** [comment]
Should there be some sort of vetting / promotion that happens before an application / platform gets it's own folder here? I imagine most of these will remain stubs for quite some time without any implementation. My suggestion would be to have a single folder or perhaps a different project even with all of the things that are on your radar. Then as you plan for implementations, they're graduated here, or perhaps to their own project. I like a mono-repo but this feels very broad as currently structured.

**Comment by a-da** [comment]
@shawnsarwar 

> [1] Should there be some sort of vetting / promotion that happens before an application / platform gets it's own folder here? 

Yes, it is the Code Review.

> [2] My suggestion would be to have a single folder

I don't see how it will help just by hiding it into a folder.
GIT submodules or separate projects are not an option see [3]. 

```bash
> tree -L 1
.
├── LICENSE
├── README.md
├── README.rst
├── ansible.com
├── argo-cd.readthedocs.io
├── aws.com
├── docker.com
├── gitlab.com
├── goharbor.io
├── google.com
├── jenkins.io
├── kubernetes.io
├── minikube.sigs.k8s.io
├── netlify.com
├── nixos.org
├── podman.io
└── terraform.io

```
vs

```bash
> tree -L 2
.
├── LICENSE
├── README.md
└── folder
    ├── ansible.com
    ├── argo-cd.readthedocs.io
    ├── aws.com
    ├── docker.com
    ├── gitlab.com
    ├── goharbor.io
    ├── google.com
    ├── jenkins.io
    ├── kubernetes.io
    ├── minikube.sigs.k8s.io
    ├── netlify.com
    ├── nixos.org
    ├── podman.io
    └── terraform.io
```

> [3] I like a mono-repo but this feels very broad as currently structured.

Indeed this is the challenge, to have a real mono-repo, very broad, otherwise it is not a mono-repo and just a repo.

**Comment by shawnsarwar** [comment]
Makes sense. If you're confident that the implementations won't be effectively hidden by the stubs then LGTM.

**Comment by emhamzahazeen** [comment]
Maybe https://www.runatlantis.io/ and/or https://terramate.io/ for quality of life. Would recommend a mono-repo approach, its add a bit of initial friction though.

Maybe .editorconfig, [commit-linting](https://github.com/conventional-changelog/commitlint) and [changelog](https://github.com/conventional-changelog/conventional-changelog ) could benefit.

**Comment by emhamzahazeen** [comment]
Otherwise LGTM

**Comment by a-da** [comment]
@emhamzahazeen 
[1] Terraform integration as plugin
Not possible, It will be insane to bind my AWS account with this repository.
Maybe Terraform for Kubernetes on Minikube in the future only.
At the moment this will be just a storage for Playbooks/Plans and Scripts

[2] versioning, commits formats and changelog
Literally no versioning is planned, no releases, only one version, latest, from the head of the main branch.

**Pull request merged**
